### ISSUE TITLE
✅ Tests général des class réalisées

### ISSUE THREAD

**Issue by MathieuSoysal** [MathieuSoysal/projetalgo-albautmoralesdaviersoysal#30]
Réalisation de tests plus approfondie sur les class ayant était finis.
- [x] reprise de l'issue #26 
- [x] test plus approfondi de la méthode run de #1 
- [x] Ajout des tests pour #10 
- [x] Approfondir les tests sur les *Stratégies* notamment en les combinant avec le run *(tests d'intégration)*
